library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

library nsl_amba, nsl_data;
use nsl_amba.apb.all;
use nsl_data.bytestream.all;
use nsl_data.endian.all;

-- APB-slave bridge to the GTR12_UPARA primitive's UPAR bus.
-- Maps a fabric-side APB transaction onto a 24-bit address /
-- 32-bit data UPAR write or read. UPARA also surfaces AHB_RSTN_O
-- and QUAD_CFG_TEST_DEC_EN, which the companion GTR12_QUADB
-- expects on its AHB_RSTN / TEST_DEC_EN inputs.
--
-- The bridge runs on a single clock supplied by the caller. The
-- wizard sources this clock from GTR12_QUADB's
-- FABRIC_CM_LIFE_CLK_O loopback; the transceiver group entity
-- exposes the same clock to its APB master so the user-facing
-- APB transactions land on the same domain.
entity apb_upar_bridge_gw5a is
  generic(
    config_c : nsl_amba.apb.config_t
    );
  port(
    clock_i : in std_ulogic;
    reset_n_i : in std_ulogic;

    apb_i : in nsl_amba.apb.master_t;
    apb_o : out nsl_amba.apb.slave_t;

    -- Generated by GTR12_UPARA; feed these into the companion
    -- GTR12_QUADB instance's AHB_RSTN / TEST_DEC_EN inputs.
    ahb_reset_n_o : out std_ulogic;
    test_dec_en_o : out std_ulogic
    );
end entity;

architecture gw5a of apb_upar_bridge_gw5a is

  component GTR12_UPARA is
    port(
      UPAR_CLK : in std_logic;
      UPAR_RST : in std_logic;

      UPAR_ADDR_S : in std_logic_vector(23 downto 0);
      UPAR_WREN_S : in std_logic;
      UPAR_READY_S : out std_logic;
      UPAR_WRDATA_S : in std_logic_vector(31 downto 0);
      UPAR_STRB_S : in std_logic_vector(7 downto 0);

      UPAR_RDDATA_S : out std_logic_vector(31 downto 0);
      UPAR_RDEN_S : in std_logic;
      UPAR_RDVLD_S : out std_logic;
      AHB_CLK_O : out std_logic;

      UPAR_BUS_WIDTH_S : in std_logic := '0';
      CSR_MODE : in std_logic_vector(4 downto 0) := "10100";

      CSR_TCK : in std_logic := '0';
      CSR_TMS : in std_logic := '0';
      CSR_TDI : in std_logic := '0';
      CSR_TDO : out std_logic;
      SPI_CLK : in std_logic := '0';
      SPI_MOSI : in std_logic := '0';
      SPI_MISO : out std_logic;
      SPI_SS : in std_logic := '0';

      FABRIC_DFT_EDT_UPDATE : in std_logic := '0';
      FABRIC_DFT_IJTAG_CE : in std_logic := '0';
      FABRIC_DFT_IJTAG_RESET : in std_logic := '0';
      FABRIC_DFT_IJTAG_SE : in std_logic := '0';
      FABRIC_DFT_IJTAG_SEL : in std_logic := '0';
      FABRIC_DFT_IJTAG_SI : in std_logic := '0';
      FABRIC_DFT_IJTAG_TCK : in std_logic := '0';
      FABRIC_DFT_IJTAG_UE : in std_logic := '0';
      FABRIC_DFT_PLL_BYPASS_CLK : in std_logic := '0';
      FABRIC_DFT_PLL_BYPASS_MODE : in std_logic := '0';
      FABRIC_DFT_SCAN_CLK : in std_logic := '0';
      FABRIC_DFT_SCAN_EN : in std_logic := '0';
      FABRIC_DFT_SCAN_IN0 : in std_logic := '0';
      FABRIC_DFT_SCAN_IN1 : in std_logic := '0';
      FABRIC_DFT_SCAN_IN2 : in std_logic := '0';
      FABRIC_DFT_SCAN_IN3 : in std_logic := '0';
      FABRIC_DFT_SCAN_IN4 : in std_logic := '0';
      FABRIC_DFT_SCAN_IN5 : in std_logic := '0';
      FABRIC_DFT_SCAN_IN6 : in std_logic := '0';
      FABRIC_DFT_SCAN_RSTN : in std_logic := '0';
      FABRIC_DFT_SHIFT_SCAN_EN : in std_logic := '0';

      QUAD_CFG_TEST_DEC_EN : out std_logic;
      AHB_RSTN_O : out std_logic
      );
  end component;

  signal address_s : unsigned(config_c.address_width-1 downto config_c.data_bus_width_l2);
  signal w_data_s : byte_string(0 to 2**config_c.data_bus_width_l2-1);
  signal w_mask_s : std_ulogic_vector(0 to 2**config_c.data_bus_width_l2-1);
  signal w_valid_s, w_ready_s : std_ulogic;
  signal r_data_s : byte_string(0 to 2**config_c.data_bus_width_l2-1);
  signal r_valid_s, r_ready_s : std_ulogic;

  signal reset_s : std_ulogic;

  signal address24_slv_s : std_logic_vector(23 downto 0);
  signal w_data_slv_s, r_data_slv_s : std_logic_vector(31 downto 0);
  signal w_mask_slv_s : std_logic_vector(7 downto 0);

begin

  address24_slv_s <= std_logic_vector(resize(address_s, 24));
  w_data_slv_s <= std_logic_vector(from_le(w_data_s));
  r_data_s <= to_le(unsigned(r_data_slv_s));
  w_mask_slv_s <= std_logic_vector(bitswap(w_mask_s & w_mask_s));

  slave: nsl_amba.apb.apb_slave
    generic map(
      config_c => config_c
      )
    port map(
      clock_i => clock_i,
      reset_n_i => reset_n_i,

      apb_i => apb_i,
      apb_o => apb_o,

      address_o => address_s,

      w_data_o => w_data_s,
      w_mask_o => w_mask_s,
      w_valid_o => w_valid_s,
      w_ready_i => w_ready_s,

      r_data_i => r_data_s,
      r_ready_o => r_ready_s,
      r_valid_i => r_valid_s
      );

  reset_s <= not reset_n_i;

  upar_inst: GTR12_UPARA
    port map(
      UPAR_ADDR_S => address24_slv_s,

      UPAR_WRDATA_S => w_data_slv_s,
      UPAR_STRB_S => w_mask_slv_s,
      UPAR_WREN_S => w_valid_s,
      UPAR_READY_S => w_ready_s,

      UPAR_RDDATA_S => r_data_slv_s,
      UPAR_RDEN_S => r_ready_s,
      UPAR_RDVLD_S => r_valid_s,

      UPAR_CLK => clock_i,
      UPAR_RST => reset_s,

      AHB_CLK_O => open,
      AHB_RSTN_O => ahb_reset_n_o,

      UPAR_BUS_WIDTH_S => '0',
      CSR_MODE => "10100",

      QUAD_CFG_TEST_DEC_EN => test_dec_en_o
      );

end architecture;
