vhdl-sources += sgmii.pkg.vhd
vhdl-sources += sgmii_driver.vhd
vhdl-sources += sgmii_pcs_rx.vhd
vhdl-sources += sgmii_pcs_tx.vhd
vhdl-sources += sgmii_autoneg.vhd

deps += nsl_data.bytestream
deps += nsl_bnoc.committed
deps += nsl_mii.link
deps += nsl_mii.flit
deps += nsl_logic.bool
deps += nsl_line_coding.ibm_8b10b
deps += nsl_io.diff
deps += nsl_io.pad
deps += nsl_io.serdes
deps += nsl_io.ddr
deps += nsl_io.delay
